# Chapter 12-02
## NumPy를 사용한다

### NumPy의 array를 생성한다

In [ ]:
# array의 작성
import numpy as np         # NumPy를 임포트
a = np.array([0, 1, 2, 3]) # array를 만듦
a                          # array를 표시

In [ ]:
# 2차원 array의 작성
b = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]])
b

In [ ]:
# array의 속성
print(b.ndim)       # 차원 수
print(b.shape)      # 각 차원의 요소 수
print(b.size)       # 크기
print(b.dtype)      # 형

In [ ]:
# 2차원 배열로 변환한다
# reshape()로 array로 변경
b2 = np.zeros(9).reshape(3, 3)
b2

In [ ]:
# 배열의 회전
# T(전치 행렬)를 표시
# 0,1,2 2,3,4 5,6,7는 3x3의 array
a = np.arange(9).reshape(3, 3)  
a                     # array 보기

In [ ]:
a.T                   # 90도 회전한 array 보기

### array를 사용한 연산

In [ ]:
# 각 요소에 1을 더함
a = np.arange(1, 10)    # 1에서 9까지의 배열을 만듦
a+1                     # 각 요소에 1을 더하여 표시

In [ ]:
# 배열의 덧셈
# 2개의 array의 각 요소를 더함
a = np.arange(1, 10)
b = np.arange(1, 10)    # 1에서 9까지의 배열을 2개 만듦
a+b                     # a의 요소와 b의 요소를 더함

In [ ]:
# 배열의 곱셈 1
# 브로드캐스팅(Broadcasting)
a = np.ones(9).reshape(3, 3) # 1로만 구성된 3×3의 array를 만듦
b = np.arange(1, 4)          # 1, 2, 3의 array를 만듦
a*b                          # 곱셈한 결과를 표시

In [ ]:
# 배열의 곱셈 2
# 브로드캐스팅을 사용하여 3x3의 array를 만든다
np.zeros((3, 1))*np.zeros((1, 3))

In [ ]:
# 요소의 합계
# 함수를 사용한 연산
# 0부터 8까지로, 3×3의 array를 만듦
a = np.arange(9).reshape(3, 3)
np.sum(a)        # 합계를 계산

In [ ]:
# 축끼리의 덧셈을 한다.
# 인수 axis를 준 연산
# [[0 1 2]
#  [3 4 5]
#  [6 7 8]]
# 위 배열의 각 축의 합계를 계산
np.sum(a, axis=0)

### 요소에의 접근

In [ ]:
# 요소에 접근한다
a = np.arange(9).reshape(3, 3) # 0부터 8까지로 3×3의 array를 만듦
a[1, 2]                        # 1, 2의 요소를 표시

In [ ]:
# 슬라이스 이용
# 슬라이스를 사용하여 요소를 추출하기
a[1:, 1:3]             # 오른쪽 아래의 2×2의 배열을 꺼냄

In [ ]:
# 인덱스에 리스트를 지정한다
# 인덱스에 리스트를 전달하여 여러 요소를 추출하기
d = np.arange(1, 10)        # 1에서 9까지의 array를 만듦
d[[1, 3, 5, 7]]             # 짝수만 꺼냄

### array 연결

In [ ]:
# 횡 방향으로 연결한다
a = np.arange(4).reshape(2, 2)      # 2×2, 0에서 3까지의 array
b = np.arange(5, 9).reshape(2, 2)   # 2×2, 5에서 8까지의 array
np.hstack((a, b))

In [ ]:
# 종 방향으로 연결한다
a = np.arange(4).reshape(2, 2)      # 2×2, 0에서 3까지의 array
b = np.arange(5, 9).reshape(2, 2)   # 2×2, 5에서 8까지의 array
np.vstack((a, b))

### array의 복사(copy)

In [ ]:
# array끼리의 대입
# 내장 리스트형과 마찬가지로 array의 대입 복사된다
# (변수가 동일한 array에 대한 참조 포함)
a = np.zeros(4)     # 4개의 0으로 array를 만듦
b = a               # b에 대입
b += 1              # 각 요소에 1을 더함
a                   # a의 내용을 표시

In [ ]:
# 존재하는 array에서 다른 array를 생성하고 싶을 때는 명시적으로 복사한다
a = np.zeros(4)     # 4개의 0으로 array를 만듦
b = a.copy()        # b에 대입
b += 1              # 각 요소에 1을 더함
a                   # a의 내용을 표시